apiVersion: v2
name: nginx
description: Nginx is a high-performance HTTP server and reverse proxy.
type: application

version: 0.1.3
appVersion: "1.29.1"

keywords:
  - nginx
  - web server
  - http
  - reverse proxy
  - load balancer
  - proxy

home: https://www.cloudpirates.io

sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/nginx

maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io

dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates

icon: https://a.storyblok.com/f/143071/512x512/9fcd98c061/nginx-logo.svg
