{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- include "postgres.annotations" . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "postgres.fullname" .)) }}
  {{- if .Values.auth.enablePostgresUser }}
  {{- $existingPostgresPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPostgresPassword = index $existingSecret.data "postgres-password" }}
  {{- end }}
  postgres-password: {{ $existingPostgresPassword | default (.Values.auth.postgresPassword | default (randAlphaNum 32) | b64enc) | quote }}
  {{- end }}
  {{- if eq (include "postgres.createUser" .) "true" }}
  {{- $existingPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingPassword = index $existingSecret.data "password" }}
  {{- end }}
  password: {{ $existingPassword | default (.Values.auth.password | default (randAlphaNum 32) | b64enc) | quote }}
  {{- end }}
{{- end }}