apiVersion: v2
name: mongodb
description: MongoDB a flexible NoSQL database for scalable, real-time data management
type: application
version: 0.1.6
appVersion: "8.0.13"
keywords:
  - mongodb
  - database
  - nosql
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/mongodb
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/5d228988dc/mongodb-logo.svg
