apiVersion: v2
name: minio
description: High Performance Object Storage compatible with Amazon S3 APIs
type: application
version: 0.2.0
appVersion: "2024.8.17"
keywords:
  - minio
  - object-storage
  - s3
  - storage
  - cloud-native
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/minio
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/5d3310f00d/minio-logo.svg
