{{- if and (not .Values.auth.existingSecret) .Values.auth.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $existingSecret := (lookup "v1" "Secret" .Release.Namespace (include "mariadb.fullname" .)) }}
  {{- $existingRootPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingRootPassword = index $existingSecret.data .Values.auth.secretKeys.rootPasswordKey }}
  {{- end }}
  {{ .Values.auth.secretKeys.rootPasswordKey }}: {{ $existingRootPassword | default (.Values.auth.rootPassword | default (randAlphaNum 32) | b64enc) | quote }}
  {{- if or .Values.auth.username .Values.auth.password }}
  {{- $existingUserPassword := "" }}
  {{- if and $existingSecret $existingSecret.data }}
    {{- $existingUserPassword = index $existingSecret.data .Values.auth.secretKeys.userPasswordKey }}
  {{- end }}
  {{ .Values.auth.secretKeys.userPasswordKey }}: {{ $existingUserPassword | default (.Values.auth.password | default (randAlphaNum 32) | b64enc) | quote }}
  {{- end }}
{{- end }}