{{- if .Values.consoleIngress.enabled -}}
{{- $fullName := include "minio.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-console
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
  {{- $annotations := merge .Values.consoleIngress.annotations .Values.commonAnnotations }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.consoleIngress.className }}
  ingressClassName: {{ .Values.consoleIngress.className }}
  {{- end }}
  {{- if .Values.consoleIngress.tls }}
  tls:
    {{- range .Values.consoleIngress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.consoleIngress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if .pathType }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  name: console
          {{- end }}
    {{- end }}
{{- end }}