apiVersion: v2
name: clusterpirate
description: Client agent for the CloudPirates Managed Observability Platform to connect your Kubernetes cluster to our infrastructure
type: application
version: 1.0.7
appVersion: "1.0.1"

keywords:
  - kubernetes
  - clusterpirate
  - cloudpirates
  - observability
  - agent

home: https://www.cloudpirates.io

maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io

dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
  - name: valkey
    version: "0.1.5"
    repository: oci://registry-1.docker.io/cloudpirates
    condition: valkey.enabled

icon: https://a.storyblok.com/f/143071/512x512/88dc07809a/cluster-pirate-logo.svg
