apiVersion: v2
name: postgres
description: The World's Most Advanced Open Source Relational Database
type: application
version: 0.2.2
appVersion: "17.6"
keywords:
  - postgres
  - postgresql
  - database
  - sql
  - relational
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/postgres
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/95e7f13e62/postgres-logo.svg
