{{- if .Values.peerDiscoveryK8sPlugin.enabled }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "rabbitmq.fullname" . }}-peer-discovery
  namespace: {{ .Release.Namespace }}
  labels: {{- include "rabbitmq.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "rabbitmq.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "rabbitmq.fullname" . }}-peer-discovery
{{- end }}