apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
  {{- with (include "rabbitmq.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.amqpPort }}
      targetPort: amqp
      name: amqp
    {{- if .Values.managementPlugin.enabled }}
    - port: {{ .Values.service.managementPort }}
      targetPort: mgmt
      name: mgmt
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      targetPort: prometheus
      name: prometheus
    {{- end }}
  selector:
    {{- include "rabbitmq.selectorLabels" . | nindent 4 }}