apiVersion: v2
name: redis
description: An open source, in-memory data structure store used as a database, cache, and message broker.
type: application
version: 0.1.6
appVersion: "8.2.1"
keywords:
  - redis
  - database
  - cache
  - in-memory
  - key-value
  - nosql
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/redis
annotations:
  category: Database
  license: Apache-2.0
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/32c74816d1/redis-logo.svg
