apiVersion: v2
name: rabbitmq
description: A messaging broker that implements the Advanced Message Queuing Protocol (AMQP)
type: application
version: 0.1.1
appVersion: "4.1.3"
keywords:
  - rabbitmq
  - message broker
  - amqp
  - messaging
  - queue
home: https://www.cloudpirates.io
sources:
  - https://github.com/CloudPirates-io/helm-charts/tree/main/charts/rabbitmq
annotations:
  category: Message Broker
  license: Apache-2.0
maintainers:
  - name: CloudPirates GmbH & Co. KG
    url: https://www.cloudpirates.io
dependencies:
  - name: common
    version: "1.x.x"
    repository: oci://registry-1.docker.io/cloudpirates
icon: https://a.storyblok.com/f/143071/512x512/aa1bd68288/rabbitmq-logo.svg
